excluded:
  - Carthage
  - vendor
  - Pods
  - Clapper-Rough-Cut/Whisper
  - Clapper-Rough-Cut/MFCC
disabled_rules:
  - colon
  - comma
  - control_statement
  - nesting
  - comment_spacing
  - multiple_closures_with_trailing_closure
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - redundant_optional_initialization
  - identifier_name
  - explicit_init
custom_rules:
  swiftgen_assets:
    name: "SwiftGen Assets"
    regex: '(UIImage|UIColor)(\.init)?\(named: ?"?.+"?(, ?in:.+?, ?compatibleWith:.+?)?\)|#imageLiteral\(resourceName: ?".+"\)'
    message: "Use Asset.<asset> instead"
    severity: error
  swiftgen_colors:
    name: "SwiftGen Colors"
    regex: '(UIColor(\.init)?|#colorLiteral)\(((red|displayP3Red):.+?,green:.+?,blue:.+?,alpha:.+?)|(white:.+?,alpha:.+?)|(hue:.+?,saturation:.+?,brightness:.+?,alpha:.+?)\)'
    message: "Use ColorName.<color> instead"
    severity: error
  swiftgen_fonts:
    name: "SwiftGen Fonts"
    regex: 'UIFont(\.init)?\(name: ?"?.+"?, ?size:.+?\)'
    message: "Use FontFamily.<family>.<variant>.size(<size>) instead"
    severity: error
  swiftgen_strings:
    name: "SwiftGen Strings"
    regex: 'NSLocalizedString'
    message: "Use L10n.key instead"
    severity: error
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - first_where
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message
  - vertical_parameter_alignment_on_call
  - let_var_whitespace

number_separator:
  minimum_length: 4

force_cast: warning
force_try:
  severity: warning

line_length: 200

cyclomatic_complexity: 13

function_body_length: 100

type_body_length:
  - 300
  - 400

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 4
  max_length:
    warning: 55
    error: 65
  excluded: iPhone
  allowed_symbols: ["_"]
identifier_name:
  min_length:
    error: 1
  excluded:
    - id
    - URL
    - GlobalAPIKey
    - to
reporter: "xcode"
